# -*- coding: utf-8 -*-
RSS_FEEDS = {
    "ایسنا": "https://www.isna.ir/rss",
    "ایرنا": "https://www.irna.ir/rss",
    "ایران اینترنشنال": "https://www.iranintl.com/fa/rss",
    "یورونیوز فارسی": "https://parsi.euronews.com/rss",
    "العربیه فارسی": "https://farsi.alarabiya.net/rss.xml",
    "Al Jazeera": "https://www.aljazeera.com/xml/rss/all.xml",
    "Al Arabiya": "https://english.alarabiya.net/tools/rss",
    "Arab News": "https://www.arabnews.com/rss.xml",
    "Gulf News": "https://gulfnews.com/rss",
    "Times of Israel": "https://www.timesofisrael.com/feed/",
    "Jerusalem Post": "https://www.jpost.com/rss/rssfeedsfrontpage.aspx",
    "Haaretz": "https://www.haaretz.com/cmlink/1.628752",
    "Daily Sabah": "https://www.dailysabah.com/rssFeed/10000",
    "Hürriyet": "https://www.hurriyet.com.tr/rss/anasayfa",
    "Anadolu Agency": "https://www.aa.com.tr/en/rss/default?cat=live",
    "France24": "https://www.france24.com/en/rss",
    "DW English": "https://rss.dw.com/rdf/rss-en-all",
    "RFI": "https://www.rfi.fr/en/rss",
    "AP News": "https://apnews.com/rss",
    "Reuters": "https://www.reutersagency.com/feed/?best-topics=middle-east",
    "CBC": "https://www.cbc.ca/cmlink/rss-world",
    "MercoPress": "https://en.mercopress.com/rss/",
    "News24": "https://www.news24.com/rss",
    "Nikkei Asia": "https://asia.nikkei.com/rss/feed/nar",
    "South China Morning Post": "https://www.scmp.com/rss/91/feed",
    "ABC News Australia": "https://www.abc.net.au/news/feed/51120/rss.xml",
}

KEYWORDS = [
    "iran", "ایران", "tehran", "تهران", "trump", "ترامپ",
    "hezbollah", "حزب الله", "israel", "اسرائیل",
    "iraq", "عراق", "pakistan", "پاکستان", "afghanistan", "افغانستان",
    "azerbaijan", "آذربایجان", "armenia", "ارمنستان", "russia", "روسیه",
    "ukraine", "اوکراین", "greece", "یونان", "turkey", "ترکیه",
    "persian gulf", "خلیج فارس", "uae", "امارات", "saudi", "عربستان",
    "qatar", "قطر", "kuwait", "کویت", "bahrain", "بحرین", "oman", "عمان",
    "iran football", "فوتبال ایران", "iran economy", "اقتصاد ایران",
    "iran sanctions", "تحریم ایران", "migration", "مهاجرت",
    "رضا پهلوی", "pahlavi",
    "بورس", "stock market", "oil price", "نفت برنت", "borsa",
]
